# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
