# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-25 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coupon', models.CharField(max_length=30)),
                ('validity', models.DateField(default=datetime.date(2019, 8, 25))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
