# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-14 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='validity',
            field=models.DateField(default=datetime.date(2019, 9, 14)),
        ),
    ]
